blog/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('posts/', PostList.as_view(), name='posts'),
    path('read/<slug:slug>/', PostDetail.as_view(), name='post'),
]

root/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls import include, path  
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('users.urls')),
    path('', include('main.urls')),
    path('', include('blog.urls')),
    
    path('comment/', include('comment.urls')),

    # path('trending/', views.trending, name='trending'),
    # path('peep/', views.peep, name = 'peep'),
    # path('test/', views.test3, name = 'test'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
     path('login/', CustomLoginView.as_view(
          redirect_authenticated_user=True, 
          template_name='users/login.html',
          authentication_form=LoginForm), 
          name='login'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
               template_name='users/password_reset_confirm.html'),
               name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
               template_name='users/password_reset_complete.html'),
               name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('register/', RegisterView.as_view(), name='users-register'),
    path('profile/edit', profile_edit, name='users-profile-edit'),
    path('profile/<user>/', profile_view, name='users-profile-view'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
import os
import shutil
from django.urls import reverse
from nanoid import generate

from main.models import Videos

def user_directory_path(instance, filename):
    path = 'users/static/profile_images/' + str(instance) 
    t = 'media/'+ path
    if os.path.exists(t):
        shutil.rmtree(t)
    filename = str(instance)+'_'+generate(size=5)+'.jpg'
    return os.path.join(path, filename)

class Profile(models.Model):
    # likedvideo = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='users/static/default.jpg', upload_to=user_directory_path)
    bio = models.TextField(default='Nothing yet')
    subscribers = models.ManyToManyField(User, related_name='subscribers')
    subscriptions = models.ManyToManyField(User, related_name='subscriptions')

    def __str__(self):
        return self.user.username

    @property
    def total_subscribers(self):
        return self.subscribers.count() 

    def save(self, *args, **kwargs):
        super().save()
        # print('ghytggy'+self.avatar.path)
        img = Image.open(self.avatar.path)
        newsize = (64, 64)
        img=img.resize(newsize)
        img=img.save(self.avatar.path)
        print(self.avatar.path)
    
    def get_absolute_url(self):
        return reverse('users-profile-view', kwargs={'user': self.user})

class Channel(models.Model):
    # profilepicpath = models.CharField(max_length=600,default="/static/playbutton.png" , null=True)
    # profilepic = models.ImageField(name='',default="/static/playbutton.png", null=True, blank=True )
    channel_name = models.CharField(max_length=50, blank=False, null=False,default="")
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(required = False, widget=forms.FileInput(
        attrs={'class': 'custom-input-file'}))
    bio = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']


class UpdateProfileAvatar(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = Profile
        fields = ['avatar']

users/views.py
from pickle import FALSE
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView
# from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm, LoginForm, UpdateProfileForm
from main.models import Videos
from .models import Channel, Profile
from django.contrib.auth import logout
from datetime import date, timedelta
from django.core.paginator import Paginator
from django.db.models import Count

class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='/')
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            # messages.success(request, f'Account created for {username}')
            channel = Channel.objects.filter(user__username = username).get()
            print(channel)
            channel.channel_name = username
            channel.save()
            return redirect(to='login')
        return render(request, self.template_name, {'form': form})

class CustomLoginView(LoginView):
    form_class = LoginForm
    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')
        if not remember_me:
            self.request.session.set_expiry(0)
            self.request.session.modified = True
        return super(CustomLoginView, self).form_valid(form)

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject'
    success_message = "Check your email " \
                      "if an account exists with the email you entered. You should receive them shortly."
    success_url = reverse_lazy('home')

class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'users/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('home')

@login_required
def profile_edit(request):
    if request.method == 'POST':
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            # messages.success(request, 'Your profile is updated successfully')
    else:
        profile_form = UpdateProfileForm(instance=request.user.profile)
    return render(request, 'users/profile_edit.html', {'profile_form': profile_form,'profile':True})

def profile_view(request, user):
    template_name = 'users/profile_view.html'
    channel = Channel.objects.filter(user__username = user).get()
    videos = Videos.objects.filter(user__username = channel.user).order_by("-datetime")
    subscriptions = channel.user.profile.subscriptions.all()

    # total_views = 0
    # total_videos = 0
    # for vid in videos:
    #     total_videos+=1
    #     total_views+=vid.views_num
    # updates = []
    # if request.user.subscriptions:
    #     for u in request.user.subscriptions.all():
    #         for v in Videos.objects.filter(user__username = u):
    #             #CHECK IF VIEWED
    #             if not v.viewed(request.user):
    #                 updates.append(v)

    sort = request.GET.get('sort')
    filter = request.GET.get('filter')

    if sort:
        if(sort=='New'):
            videos = videos.order_by('-datetime')
        elif(sort=='Most viewed') or (sort=='Most+viewed'):
            videos  = videos.order_by('-views')
        elif(sort=='Popular'):
            videos  = videos.annotate(num_likes=Count('likes')).order_by('-num_likes')
    else:
        videos = videos.all()
    if filter:
        if(filter=='month'):
            startdate = date.today()
            enddate = startdate - timedelta(days=30)
            videos = videos.filter(datetime__range=[enddate, startdate])
        elif(filter=='3month'):
            startdate = date.today()
            enddate = startdate - timedelta(days=60)
            videos = videos.filter(datetime__range=[enddate, startdate])
        elif(filter=='6month'):
            startdate = date.today()
            enddate = startdate - timedelta(days=180)
            videos = videos.filter(datetime__range=[enddate, startdate])

    paginator = Paginator(videos, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)


    if (channel.user == request.user):
        owner = True 
    else:
        owner = False
    context={}
    context['page_obj']=page_obj
    context['subsriptions'] = subscriptions
    context['channel'] = channel
    # context['total_views'] = total_views
    # context['total_videos'] = total_videos
    # context['updates'] = updates
    context['owner'] = owner
    return render(request, template_name, context)

class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')

users/templates/users/change_password.html
{% extends "main/base.html" %}
{% block content %}
<div class="container-fluid min-vh-100">
    <div class="form-content my-3 p-3">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}

                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_old_password">Old Password</label>
                                            <input type="password" name="old_password" autocomplete="new-password"
                                                    class="form-control" required id="id_old_password"
                                                    placeholder="Enter Old Password"/>
                                            <span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password1">New Password</label>
                                            <input type="password" name="new_password1" autocomplete="new-password"
                                                    class="form-control" required id="id_new_password1"
                                                    placeholder="Enter New Password"/>
                                            <span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                            <input type="password" name="new_password2" autocomplete="new-password"
                                                    required id="id_new_password2" class="form-control"
                                                    placeholder="Confirm New Password"/>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                            
                                            <button type="submit" class="col-md-12 btn text-white btn-outline-light" style="background-color:#7E0000 " id="reset">Update Password</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends "main/base.html" %}
{% block content %}
{% load static %}
<div class="container-fluid has-bg-img p-0 min-vh-100 "
style="background-image: url({% static '/bg/200.gif' %});
 background-repeat: no-repeat; 
 background-size: cover; 
 background-position: center center;">

    
    <div class="form-content my-3 p-3 mt-0">
        <div class="row d-flex justify-content-center ">
            <div class="col-md-4">
                <div class="card shadow-lg border border-secondary rounded-lg mt-0 mb-3 " >
                    <div class="card-header justify-content-center">
                        <h3 class="font-weight-light my-1 text-center">Sign In</h3>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <div id="form_errors">
                                {% for key, value in form.errors.items %}
                                    <strong>{{ value }}</strong>
                                {% endfor %}
                            </div>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        {% comment %} <a href="{% url 'social:begin' 'github' %}"
                                                class="btn btn-link btn-lg active btn-block">Sign in with GitHub</a>
                                        <a href="{% url 'social:begin' 'google-oauth2' %}"
                                                class="btn btn-link btn-lg active btn-block">Sign in with Google</a>
                                        <hr>
                                        <p class="text-center"><strong>OR</strong></p>
                                        <hr> {% endcomment %}
                                        <label class="small mb-1">Username</label>
                                        {{ form.username }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <label class="small mb-1">Password</label>
                                        {{ form.password }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <!-- Add a Remember me functionality -->
                                        {{ form.remember_me }}
                                        <label> Remember me</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button name="login" class="col-md-12 m-btn-danger btn-outline-light p-1" id="login">Sign in</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url 'users-register' %}">Don't have an account yet?</a><br>
                            <a href="{% url 'password_reset' %}"><i>Forgot Password?</i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>
</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>

{% endblock content %}

users/templates/users/logout.html
{% extends "main/base.html" %}
{% block content %}
<div class="container-fluid mx-auto py-5 min-vh-100 ">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">You have been logged out</h5>
        <p class="card-text">
            Bye
        </p>
        <br><hr><a href="{% url 'login' %}" class="btn btn-primary">Sign in again</a>
        </div>
    </div>
</div>


{% endblock content %}

users/templates/users/password_reset.html
{% extends "main/base.html" %}
{% block content %}
<div class="container-fluid min-vh-100">
    <div class="form-content my-3 p-3">
        <div class="row d-flex justify-content-center">
            <div class="col-md-4">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="card-header justify-content-center">
                        <div id="error_div"></div>
                        <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                    </div>
                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <div id="form_errors">
                                {% for key, value in form.errors.items %}
                                    <strong>{{ value }}</strong>
                                {% endfor %}
                            </div>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_email">Email</label>
                                    <input type="email" name="email"  class="form-control"
                                            autocomplete="email" maxlength="254" required id="id_email"
                                            placeholder="Enter email">
                                </div>
                            </div>
                            <br>

                        </div>
                            <div class="form-row">
                                <div class="col-md-10 offset-md-1">
                                <div class="form-group mt-0 mb-1">
                                    <button type="submit" class="col-md-12 m-btn-danger text-white btn-outline-light">Submit
                                    </button>
                                </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small">
                            <a href="{% url 'users-register' %}">Create A New Account</a><br><br>
                            <a href="{% url 'login' %}">Back To Login</a><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/profile_edit.html
{% extends "main/base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
	<div class="container-fluid mx-auto py-5 min-vh-100 ">
		<div class="row d-flex justify-content-center align-items-center">
			<div class="col col-xxl-9 ">
				<div class="card"  style="background-color:#222">
					<div class="form-content">
						<form method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="rounded-top px-4 py-3 text-white d-flex flex-row border-bottom border-secondary" style="height:250px; background-color:161a1d">
								<div class="ms-2 mt-2 d-flex flex-column text-center" style="width: 150px; height: 150px;">
									<img src={{user.profile.avatar.url}} class="justify-content-center img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">
									<p>{{user}}</p>
								</div>
								<div class="container  px-4 py-3 ms-2 mt-2">
									<div class="row ">
										<div class="col">
											<nav>
												<div class="nav nav-tabs" id="nav-tab" role="tablist">
													<button class="nav-link active bg-transparent" id="description-tab" data-bs-toggle="tab" data-bs-target="#description" 
													type="button" role="tab" aria-controls="description" aria-selected="true">Description</button>
													{% comment %} <button class="nav-link" id="totalvideos-tab" data-bs-toggle="tab" data-bs-target="#totalvideos" 
													type="button" role="tab" aria-controls="totalvideos" aria-selected="false">Total videos</button>
													<button class="nav-link" id="totallikes-tab" data-bs-toggle="tab" data-bs-target="#totallikes" 
													type="button" role="tab" aria-controls="totallikes" aria-selected="false">Contact</button> {% endcomment %}
												</div>
											</nav>
											<div class="tab-content p-1" id="nav-tabContent">
												<div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
													{{ user.profile.bio }}</div>
												<div class="tab-pane fade" id="totalvideos" role="tabpanel" aria-labelledby="totalvideos-tab">
													..32132.</div>
												<div class="tab-pane fade" id="totallikes" role="tabpanel" aria-labelledby="totallikes-tab">
													..12321.</div>
											</div>
										</div>
									</div>
								</div>

							</div>

							<div class="container mt-3">
								<div class="form-group d-flex " >
									{{ profile_form.avatar }}
									<label for="id_avatar" class="btn btn-tertiary js-labelFile  " style="margin: 0;">
										<span class="js-fileName nowrap">Upload new profile picture</span>
									</label>
								</div>
								<br>
								<label class=" mb-1">Edit description:</label> {{ profile_form.bio }}
								<br><br>

								<div class="row">
									<div class="col  justify-content-start d-flex">
										<button class=" m-btn-danger btn-outline-light p-1">
											<a class="p-0 m-0 nav-item nav-link text-white" style= "text-decoration: none;" href="{% url 'password_change' %}">Change password</a>
										</button>
									</div>
									<div class="col justify-content-end d-flex">
										<button type="submit" class="m-btn-danger btn-outline-light p-1">Save Changes</button>
									</div>
								</div>

								</div>

								</div>
							</div>

							{% comment %} <button type="reset" class="btn btn-dark ">Reset</button> {% endcomment %}
						</form>
					</div>
					

				</div>

				{% comment %} <div class="row m-3">
					{% if videos %}
						{% for video in videos %}
							<div class="col-md-4 d-flex align-items-stretch " style="width:33%">
								<div class="card bcontent flex-fill p-0 border border-secondary">
									<div class="card-body p-0 ">
									<a  href="/video/{{ video.id }}">
										<img class="gif" src="{{ video.thumbnailpath}}" width="100%" height="200px;"></img>
									</a>
									</div>
									<div class = "card-footer py-0 ">
									<p class="text-center m-0 p-0">{{video.title|truncatechars:42}}</p>
									<tr>
										<th class ="text-center">{{video.number_of_views}} Views</th>
										<th>                     
										{% if video.user %}
											<a href="/profile/{{video.user}}/">{{video.user}}</a>
										{% else %}
											anon
										{% endif %}
										</th>
									</tr>
									</div>
								</div>
							</div> 
							{% if forloop.counter|divisibleby:3 %}
								<div class="row my-3"></div>
							{% endif %}
						{% endfor %}
					{% else %}
						<p>Nothing yet</p>
					{% endif %}
				</div> {% endcomment %}
			</div>
		</div>


			{% if user_form.errors %}
			<div class="alert alert-danger alert-dismissible" role="alert">
				<div id="form_errors">
					{% for key, value in user_form.errors.items %}
						<strong>{{ value }}</strong>
					{% endfor %}
				</div>
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
		{% endif %}
	</div>
{% endblock content %}